### PR TITLE
Akuli! What's up?

### PR DESCRIPTION
**Pull request by ThePhilgrim**
Hey @Akuli ! I'm back from travelling and will be coding for a few months. The guys on IRC say you haven't been on IRC for a long while. What's going on, you had enough? :P

Let me know if you feel like coding a bit together! It would be fun! :)

### CODE REVIEW

**Comment by Akuli** [comment]
Hi :) I haven't had much spare time lately, and many times when I go to IRC, I end up spending hours explaining something to someone. I will probably be back on IRC after Christmas.

I would like to work on something :)

**Comment by ThePhilgrim** [comment]
I got it! Can imagine that IRC drains a lot of your time and energy. It's the burden of being the master :P

Cool, I'll be in Sweden around Christmas, which means I'll have a lot of time for coding. Maybe we could think of some cool projects until then? I'm doing some javascript stuff now since I'd like to get better at it. But I'd be up for anything fun! Would love to maybe write some database/API stuff to learn.

**Comment by ThePhilgrim** [comment]
@Akuli Hey man! Are you on the computer this evening? I'm really trying to understand a git and $PATH thing.. But I can't figure it out.. I would need 10 minutes of your time to explain how something works.

**Comment by ThePhilgrim** [comment]
@Akuli 
Hey! I was hoping to get some help with deprecated tkinter. I have a new Mac and trying to open my program "Trans-Calc".

When I open the program, I get the error message `DEPRECATION WARNING: The system version of Tk is deprecated and may be removed in a future release. Please don't rely on it. Set TK_SILENCE_DEPRECATION=1 to suppress this warning.` and the UI is bugged (I can't see any text fields or buttons).

After installing Python 3.10 via Homebrew, they said 

```
tkinter is no longer included with this formula, but it is available separately: 
    brew install python-tk@3.10
```
    
I ran this command, but I still got the same issue. 

I tried to follow this answer on Stackoverflow https://stackoverflow.com/questions/72472167/deprecation-warning-the-system-version-of-tk-is-deprecated-m1-mac-in-vs-code/72472483#72472483 I still cannot get it to work.

The only thing I didn't try is `export PATH="/opt/homebrew/Cellar/tcl-tk/bin:$PATH`. The reason I didn't try this is because if this doesn't work, I don't know how to reverse an `export PATH` command. Somebody in IRC said it's risky to hard code the PATH, but I don't exactly know what he meant by that. I was hoping that you could help me figure this out. 

Please let me know if you have an idea.

**Pull request closed without merging**
